raise StandardError, not Exception for errors
Replaced all instances of raising Exception with raising StandardError,
so that puppet can properly catch the errors and report them.

This fixes the error reporting around a missing scenario:

    # puppet agent -t
    Error: Could not run Puppet configuration client: scenario must be defined in config.yaml
    Error: Could not run: can't convert Puppet::Util::Log into Integer

After changing this to StandardError the Puppet::Util::Log error is no
longer reported and you get the following instead:

    # puppet agent -t
    Error: Failed to apply catalog: scenario must be defined in config.yaml