Ensure class list of never nil
It the class list for Puppet::Node is ever
nil, Puppet blow up with the error:

  Error: Invalid tag "" on node setup

This commit adds logic to ensure that it is
set to [] when no classes need to be added.